# Generated by Django 4.0.1 on 2022-01-03 23:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import staff.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffID', models.CharField(blank=True, default=staff.models.gen_id, max_length=255, null=True, verbose_name='user id')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='last name')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='email address')),
                ('contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='contact')),
                ('gender', models.CharField(blank=True, max_length=255, null=True, verbose_name='gender')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='uuid')),
                ('role', models.CharField(blank=True, default={('MANAGER', 'MANAGER'), ('PHARMACIST', 'PHARMACIST')}, max_length=255, null=True, verbose_name='role')),
                ('profile_image', models.TextField(blank=True, null=True, verbose_name='profile image')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_staff', models.BooleanField(blank=True, default=True, null=True)),
                ('is_superuser', models.BooleanField(blank=True, default=False, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pharm.branch')),
            ],
            options={
                'db_table': 'staff',
                'ordering': ('-date_joined',),
            },
        ),
    ]
